services:
  company-api:
    image: company-api
    build:
      context: .
      dockerfile: ./Company/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

  background-check-api:
    image: background-check-api
    build:
      context: .
      dockerfile: ./BackgroundCheck/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

  government-directory-api:
    image: government-directory-api
    build:
      context: .
      dockerfile: ./GovernmentDirectory/Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

  temporal-worker-app:
    image: temporal-worker-app
    build:
      context: .
      dockerfile: ./Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

